// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI0qpGuP2lo1td4tzngBZnONVpu-u6xDI',
    appId: '1:898659227370:web:3fd9d018b3b507ec4ee993',
    messagingSenderId: '898659227370',
    projectId: 'dukcapil-9e125',
    authDomain: 'dukcapil-9e125.firebaseapp.com',
    storageBucket: 'dukcapil-9e125.firebasestorage.app',
    measurementId: 'G-MEZYRVXSG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7yqQsTe_8Klgc001uXyNSs3eOYJnNAi0',
    appId: '1:898659227370:android:e24a5dd8308dbd6d4ee993',
    messagingSenderId: '898659227370',
    projectId: 'dukcapil-9e125',
    storageBucket: 'dukcapil-9e125.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI0qpGuP2lo1td4tzngBZnONVpu-u6xDI',
    appId: '1:898659227370:web:6b89320e4c6af5144ee993',
    messagingSenderId: '898659227370',
    projectId: 'dukcapil-9e125',
    authDomain: 'dukcapil-9e125.firebaseapp.com',
    storageBucket: 'dukcapil-9e125.firebasestorage.app',
    measurementId: 'G-F1J1TJJTMG',
  );
}
